/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2026-02-17 08:54:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>My Profile</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            background: linear-gradient(to right, #f4f6fb, #e1e8f5);\r\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Navbar */\r\n");
      out.write("        .navbar-custom {\r\n");
      out.write("            background: linear-gradient(90deg, #6a0dad, #4b0082);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar-custom .navbar-brand {\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            font-size: 1.3rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-card {\r\n");
      out.write("            max-width: 700px;\r\n");
      out.write("            margin: 60px auto;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            box-shadow: 0 12px 35px rgba(0,0,0,0.15);\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-header {\r\n");
      out.write("            background: linear-gradient(90deg, #6a0dad, #4b0082);\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            padding: 30px 20px;\r\n");
      out.write("            border-radius: 20px 20px 0 0;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-icon {\r\n");
      out.write("            font-size: 60px;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-header h3 {\r\n");
      out.write("            font-size: 1.8rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-header p {\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            opacity: 0.85;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-body {\r\n");
      out.write("            padding: 30px 25px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-row {\r\n");
      out.write("            padding: 15px 0;\r\n");
      out.write("            border-bottom: 1px solid #eee;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .label {\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            color: #555;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .badge {\r\n");
      out.write("            font-size: 0.95rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Buttons */\r\n");
      out.write("        .btn-outline-light {\r\n");
      out.write("            border-color: #fff;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-outline-light:hover {\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("            color: #6a0dad;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-danger {\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- NAVBAR -->\r\n");
      out.write("<nav class=\"navbar navbar-dark navbar-custom px-4\">\r\n");
      out.write("    <a class=\"navbar-brand fw-bold\" href=\"home\">SannidhiGS_Xworkz_Module</a>\r\n");
      out.write("\r\n");
      out.write("    <div>\r\n");
      out.write("        <a href=\"home\" class=\"btn btn-outline-light me-2\">Home</a>\r\n");
      out.write("        <a href=\"logout\" class=\"btn btn-danger\">Logout</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- PROFILE CARD -->\r\n");
      out.write("<div class=\"card shadow profile-card\">\r\n");
      out.write("\r\n");
      out.write("    <!-- HEADER -->\r\n");
      out.write("    <div class=\"profile-header\">\r\n");
      out.write("        <div class=\"profile-icon\">👤</div>\r\n");
      out.write("        <h3>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\r\n");
      out.write("        <p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- BODY -->\r\n");
      out.write("    <div class=\"card-body\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row profile-row\">\r\n");
      out.write("            <div class=\"col-4 label\">Name</div>\r\n");
      out.write("            <div class=\"col-8\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row profile-row\">\r\n");
      out.write("            <div class=\"col-4 label\">Email</div>\r\n");
      out.write("            <div class=\"col-8\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row profile-row\">\r\n");
      out.write("            <div class=\"col-4 label\">Phone</div>\r\n");
      out.write("            <div class=\"col-8\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.phoneNumber}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row profile-row\">\r\n");
      out.write("            <div class=\"col-4 label\">Gender</div>\r\n");
      out.write("            <div class=\"col-8\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.gender}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row profile-row\">\r\n");
      out.write("            <div class=\"col-4 label\">Age</div>\r\n");
      out.write("            <div class=\"col-8\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.age}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row profile-row\">\r\n");
      out.write("            <div class=\"col-4 label\">Account Status</div>\r\n");
      out.write("            <div class=\"col-8\">\r\n");
      out.write("                <span class=\"badge bg-success\">Active</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
