/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2026-02-17 08:53:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Register</title>\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            background: linear-gradient(to right, #f4f6fb, #e1e8f5);\r\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navy-navbar {\r\n");
      out.write("            background: linear-gradient(90deg, #6a0dad, #4b0082);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card {\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            box-shadow: 0 12px 35px rgba(0,0,0,0.2);\r\n");
      out.write("            padding: 40px;\r\n");
      out.write("            background-color: #ffffff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h3 {\r\n");
      out.write("            color: #4b0082;\r\n");
      out.write("            font-size: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        label {\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input.form-control, select.form-select {\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            padding: 12px;\r\n");
      out.write("            border: 1px solid #ced4da;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input.form-control:focus, select.form-select:focus {\r\n");
      out.write("            box-shadow: 0 0 8px rgba(106, 13, 173, 0.5);\r\n");
      out.write("            border-color: #6a0dad;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-primary {\r\n");
      out.write("            background-color: #6a0dad;\r\n");
      out.write("            border-color: #6a0dad;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-primary:hover {\r\n");
      out.write("            background-color: #4b0082;\r\n");
      out.write("            border-color: #4b0082;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .error {\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("            color: red;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .container {\r\n");
      out.write("            max-width: 650px; /* Larger form width */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        a {\r\n");
      out.write("            color: #6a0dad;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        a:hover {\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .text-danger {\r\n");
      out.write("            font-size: 0.95rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Add spacing between inputs */\r\n");
      out.write("        .mb-3 {\r\n");
      out.write("            margin-bottom: 1.3rem !important;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Responsive adjustments */\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .card {\r\n");
      out.write("                padding: 30px 20px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"navbar navbar-dark navy-navbar\">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("        <!-- LOGO + APP NAME -->\r\n");
      out.write("        <a class=\"navbar-brand d-flex align-items-center\" href=\"index\">\r\n");
      out.write("            <img src=\"Xworkz.png\" alt=\"Xworkz Logo\" height=\"45\" class=\"me-2\">\r\n");
      out.write("            <span class=\"fw-bold fs-5\">SannidhiGS App</span>\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <!-- ACTION BUTTONS -->\r\n");
      out.write("        <div>\r\n");
      out.write("            <a href=\"signUp\" class=\"btn btn-outline-light me-2\">Sign Up</a>\r\n");
      out.write("            <a href=\"signInPage\" class=\"btn btn-warning\">Sign In</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container d-flex justify-content-center align-items-center min-vh-100\">\r\n");
      out.write("    <div class=\"col-md-8\">\r\n");
      out.write("        <div class=\"card shadow-lg\">\r\n");
      out.write("            <h3 class=\"text-center fw-bold mb-4\">Create Account</h3>\r\n");
      out.write("\r\n");
      out.write("            <p class=\"text-danger text-center fw-bold\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMsg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("            <form action=\"registerUser\" method=\"post\" onsubmit=\"return validateForm();\">\r\n");
      out.write("\r\n");
      out.write("                <!-- NAME -->\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label class=\"fw-semibold\">Name</label>\r\n");
      out.write("                    <input type=\"text\" name=\"name\" id=\"name\" class=\"form-control\" oninput=\"validateName()\">\r\n");
      out.write("                    <span id=\"nameError\" class=\"error\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- EMAIL -->\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label class=\"fw-semibold\">Email</label>\r\n");
      out.write("                    <input type=\"email\" name=\"email\" id=\"email\" class=\"form-control\" oninput=\"validateEmail()\">\r\n");
      out.write("                    <span id=\"emailError\" class=\"error\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- PHONE -->\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label class=\"fw-semibold\">Phone Number</label>\r\n");
      out.write("                    <input type=\"text\" name=\"phoneNumber\" id=\"phone\" class=\"form-control\" maxlength=\"10\" oninput=\"validatePhone()\">\r\n");
      out.write("                    <span id=\"phoneError\" class=\"error\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- AGE -->\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label class=\"fw-semibold\">Age</label>\r\n");
      out.write("                    <input type=\"number\" name=\"age\" id=\"age\" class=\"form-control\" oninput=\"validateAge()\">\r\n");
      out.write("                    <span id=\"ageError\" class=\"error\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- GENDER -->\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label class=\"fw-semibold\">Gender</label>\r\n");
      out.write("                    <select name=\"gender\" id=\"gender\" class=\"form-select\">\r\n");
      out.write("                        <option value=\"\">Select</option>\r\n");
      out.write("                        <option>Male</option>\r\n");
      out.write("                        <option>Female</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                    <span id=\"genderError\" class=\"error\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- PASSWORD -->\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label class=\"fw-semibold\">Password</label>\r\n");
      out.write("                    <input type=\"password\" name=\"password\" id=\"password\" class=\"form-control\" oninput=\"validatePassword()\">\r\n");
      out.write("                    <span id=\"passwordError\" class=\"error\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- CONFIRM PASSWORD -->\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label class=\"fw-semibold\">Confirm Password</label>\r\n");
      out.write("                    <input type=\"password\" name=\"confirmPassword\" id=\"confirmPassword\" class=\"form-control\" oninput=\"validateConfirmPassword()\">\r\n");
      out.write("                    <span id=\"confirmPasswordError\" class=\"error\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <button class=\"btn btn-primary w-100 fw-bold mt-3\">Register</button>\r\n");
      out.write("\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    function validateName() {\r\n");
      out.write("        const name = document.getElementById(\"name\").value;\r\n");
      out.write("        const regex = /^[A-Za-z ]+$/;\r\n");
      out.write("        document.getElementById(\"nameError\").innerText =\r\n");
      out.write("            (!regex.test(name) && name !== \"\") ? \"Only alphabets allowed\" : \"\";\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function validateEmail() {\r\n");
      out.write("        const email = document.getElementById(\"email\").value;\r\n");
      out.write("        const regex = /^[a-zA-Z0-9._%+-]+@(gmail\\.com|outlook\\.com)$/;\r\n");
      out.write("        document.getElementById(\"emailError\").innerText =\r\n");
      out.write("            (!regex.test(email) && email !== \"\") ? \"Email must be gmail.com or outlook.com\" : \"\";\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function validatePhone() {\r\n");
      out.write("        const phone = document.getElementById(\"phone\").value;\r\n");
      out.write("        document.getElementById(\"phoneError\").innerText =\r\n");
      out.write("            (!/^[0-9]{10}$/.test(phone) && phone !== \"\") ? \"Enter valid 10-digit number\" : \"\";\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function validateAge() {\r\n");
      out.write("        const age = document.getElementById(\"age\").value;\r\n");
      out.write("        document.getElementById(\"ageError\").innerText =\r\n");
      out.write("            (age < 5 || age > 100) ? \"Age must be between 5 and 100\" : \"\";\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function validatePassword() {\r\n");
      out.write("        const pwd = document.getElementById(\"password\").value;\r\n");
      out.write("        document.getElementById(\"passwordError\").innerText =\r\n");
      out.write("            (pwd.length < 4) ? \"Password must be at least 4 characters\" : \"\";\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function validateConfirmPassword() {\r\n");
      out.write("        const pwd = document.getElementById(\"password\").value;\r\n");
      out.write("        const cpwd = document.getElementById(\"confirmPassword\").value;\r\n");
      out.write("        document.getElementById(\"confirmPasswordError\").innerText =\r\n");
      out.write("            (pwd !== cpwd) ? \"Passwords do not match\" : \"\";\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function validateForm() {\r\n");
      out.write("        validateName();\r\n");
      out.write("        validateEmail();\r\n");
      out.write("        validatePhone();\r\n");
      out.write("        validateAge();\r\n");
      out.write("        validatePassword();\r\n");
      out.write("        validateConfirmPassword();\r\n");
      out.write("\r\n");
      out.write("        return Array.from(document.querySelectorAll(\".error\"))\r\n");
      out.write("            .every(span => span.innerText === \"\");\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
